### ISSUE TITLE
renzu_status

### ISSUE THREAD

**Issue by SalvGallo** [renzuzu/renzu_illness#8]
Hi, Renzuzu, I'm having an issue with this script because I'm using your status script and I don't see if there's a way to set the illness to work with this status or not.  Thank you by advance.

This is the F8 error.
![image](https://user-images.githubusercontent.com/92991722/222950493-18acf0f3-18fb-4aa8-b4ca-13f8c3441812.png)

**Comment by renzuzu** [comment]
this resource is built only with esx_status table pattern.

**Comment by renzuzu** [comment]
now supports renzu_status
